// SPDX-License-Identifier: GPL-3.0-or-later
//
// Scans `wiki/*.md` at build time and emits a flat array of
// `(page_name, line_number, byte_offset, byte_len)` for the runtime
// full-text search. Keeping the index small means avoiding a second copy
// of the wiki text in the binary; we slice into the page contents
// returned by `wiki::get_page` at lookup time.
//
// Linear scan is fast enough at this corpus size (~25 pages × ~150 lines
// = ~4000 entries; a case-insensitive scan completes well under 10ms),
// so we skip the inverted-index complexity and keep the binary small.

use std::env;
use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .expect("CARGO_MANIFEST_DIR is unset; this build script requires cargo-driven build"),
    );
    let wiki_dir = manifest_dir.join("wiki");
    let out_dir = PathBuf::from(
        env::var_os("OUT_DIR")
            .expect("OUT_DIR is unset; this build script requires cargo-driven build"),
    );
    let dest = out_dir.join("wiki_index.rs");

    // `cargo:rerun-if-changed=<dir>` fires when entries are added/removed
    // (directory mtime), but historically NOT on in-place edits to existing
    // files. NPKG.4: emit one `cargo:rerun-if-changed` per file inside the
    // loop so editing AND deleting wiki pages both invalidate the index.
    // Keep the directory entry too — it covers the edge case where a wiki
    // page is added between two builds (the loop below sees the new file
    // and emits its rerun-if-changed for the next build).
    println!("cargo:rerun-if-changed=wiki");
    println!("cargo:rerun-if-changed=build.rs");

    // Issue #376: emit `proteus version --json` metadata at build time so the
    // runtime doesn't shell out. Each value falls back to a clearly-tagged
    // sentinel rather than panicking — reproducible-build environments and
    // source tarballs without `.git/` must still compile.
    //
    // `cargo:rerun-if-env-changed` lines below ensure CI / reproducible-build
    // pipelines that rewrite these env vars invalidate the cached value.
    println!("cargo:rerun-if-env-changed=PROTEUS_GIT_SHA");
    println!("cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH");
    println!("cargo:rerun-if-env-changed=TARGET");
    emit_build_metadata(&manifest_dir);

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    match fs::read_dir(&wiki_dir) {
        Ok(read_dir) => {
            for entry in read_dir.flatten() {
                let path = entry.path();
                // NPKG.4: track every file we read so cargo invalidates this
                // script when any wiki page is edited in place.
                println!("cargo:rerun-if-changed={}", path.display());
                if path.extension().and_then(OsStr::to_str) != Some("md") {
                    continue;
                }
                let Some(stem) = path.file_stem().and_then(OsStr::to_str) else {
                    continue;
                };
                // `_index.md` is the curated TOC page; it mentions every other
                // page by name, so leaving it in the search index would always
                // outrank the actual content for broad queries. Skip at index
                // build time and keep `wiki::CURATED_INDEX_PAGE` in sync.
                if stem == "_index" {
                    continue;
                }
                entries.push((stem.to_string(), path));
            }
        }
        Err(e) => {
            // NPKG.3 / B12: never panic on a wiki-dir read failure. EACCES
            // (read-restricted source tree) and ENOENT (wiki vendor stripped
            // upstream) are both legitimate environments — emit a clear
            // cargo:warning and ship an empty index. The runtime full-text
            // search will report "no matches" rather than crashing the build.
            println!(
                "cargo:warning=proteus build.rs: cannot read wiki dir {}: {} \
                 (continuing with empty wiki index — `proteus wiki` search will be empty)",
                wiki_dir.display(),
                e
            );
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = Vec::with_capacity(64 * 1024);
    writeln!(
        out,
        "// generated by build.rs — do not edit by hand\n\
         //\n\
         // Each entry is (page_name, line_number, byte_offset, byte_len);\n\
         // resolve to text via `&wiki::get_page(page).unwrap()[off..off+len]`.\n\
         pub static WIKI_LINES: &[(&str, u32, u32, u32)] = &["
    )
    .unwrap();

    for (name, path) in &entries {
        // NPKG.3 / B12: use `expect` with a clear, actionable message
        // rather than a bare panic!. Treat read errors as fatal here only
        // because the file was discoverable a moment ago — failing to read
        // a file we already saw in the dir listing means a real bug
        // (concurrent delete, mid-build chmod) the operator needs to know
        // about, not a packaging environment we can paper over.
        let content = fs::read_to_string(path).unwrap_or_else(|e| {
            panic!(
                "proteus build.rs: cannot read wiki page {}: {e}\n\
                 hint: this file appeared in fs::read_dir but read_to_string failed; \
                 check filesystem permissions or concurrent-modification.",
                path.display()
            )
        });
        let mut byte_offset: usize = 0;
        let mut line_no: u32 = 0;
        for line in content.split_inclusive('\n') {
            line_no += 1;
            let trimmed = line.trim_end_matches('\n');
            // Skip blank lines: they can't match a search term.
            if !trimmed.trim().is_empty() {
                writeln!(
                    out,
                    "    ({}, {}, {}, {}),",
                    rust_str(name),
                    line_no,
                    byte_offset,
                    trimmed.len()
                )
                .unwrap();
            }
            byte_offset += line.len();
        }
    }
    writeln!(out, "];").unwrap();

    write_if_changed(&dest, &out);
}

/// Emit a `&str` literal that round-trips every char of `s` losslessly.
/// Backslashes, quotes, newlines, tabs, and other control characters are
/// escaped; everything else (including non-ASCII letters and em-dashes)
/// is passed through verbatim — `rustc` accepts arbitrary UTF-8 in `"..."`.
fn rust_str(s: &str) -> String {
    let mut buf = String::with_capacity(s.len() + 2);
    buf.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => buf.push_str("\\\\"),
            '"' => buf.push_str("\\\""),
            '\n' => buf.push_str("\\n"),
            '\r' => buf.push_str("\\r"),
            '\t' => buf.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                buf.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => buf.push(c),
        }
    }
    buf.push('"');
    buf
}

/// Issue #376: stamp git sha, rustc version, target triple, and a
/// reproducible-friendly build timestamp into `cargo:rustc-env` lines so the
/// runtime can read them via `env!(...)` without shelling out at startup.
///
/// Every probe is best-effort: a missing `.git/`, an absent `rustc` on PATH,
/// or a sandbox that strips env vars all degrade to the literal string
/// `"unknown"` rather than failing the build. Source tarballs and Gentoo
/// ebuilds set `PROTEUS_GIT_SHA` / `SOURCE_DATE_EPOCH` explicitly to recover
/// the values the in-tree probes would have picked up.
fn emit_build_metadata(manifest_dir: &Path) {
    let git_sha = env::var("PROTEUS_GIT_SHA")
        .ok()
        .filter(|s| !s.is_empty())
        .or_else(|| git_short_sha(manifest_dir))
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=PROTEUS_GIT_SHA={git_sha}");

    let build_time = reproducible_build_time();
    println!("cargo:rustc-env=PROTEUS_BUILD_TIME={build_time}");

    let rustc = rustc_version().unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=PROTEUS_RUSTC_VERSION={rustc}");

    // `TARGET` is always set by cargo for the active build; fall back only
    // out of paranoia for hand-rolled invocations.
    let target = env::var("TARGET").unwrap_or_else(|_| "unknown".to_string());
    println!("cargo:rustc-env=PROTEUS_TARGET={target}");
}

/// `git rev-parse --short HEAD` from the manifest dir, or `None` if git is
/// unavailable or the tree isn't a checkout (source tarball).
fn git_short_sha(manifest_dir: &Path) -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .current_dir(manifest_dir)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let s = String::from_utf8(output.stdout).ok()?.trim().to_string();
    if s.is_empty() { None } else { Some(s) }
}

/// `rustc -V` so the runtime can surface the toolchain that built the binary.
/// Newline-trimmed; "unknown" fallback wired by the caller.
fn rustc_version() -> Option<String> {
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
    let output = Command::new(rustc).arg("-V").output().ok()?;
    if !output.status.success() {
        return None;
    }
    let s = String::from_utf8(output.stdout).ok()?.trim().to_string();
    if s.is_empty() { None } else { Some(s) }
}

/// Pick a build timestamp suitable for reproducible builds: prefer
/// `SOURCE_DATE_EPOCH` (the cross-distro convention) when set, otherwise the
/// current UTC time. Formatted as ISO-8601 `YYYY-MM-DDTHH:MM:SSZ`.
fn reproducible_build_time() -> String {
    let secs = env::var("SOURCE_DATE_EPOCH")
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or_else(|| {
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs())
                .unwrap_or(0)
        });
    format_iso8601_utc(secs)
}

/// Hand-rolled UTC ISO-8601 — mirrors `commands::now_iso8601` so we stay
/// zero-dep. Civil-from-days algorithm by Howard Hinnant (public domain).
fn format_iso8601_utc(mut t: u64) -> String {
    let s = (t % 60) as u32;
    t /= 60;
    let mi = (t % 60) as u32;
    t /= 60;
    let h = (t % 24) as u32;
    t /= 24;
    let mut days = t as i64;
    days += 719_468;
    let era = days.div_euclid(146_097);
    let doe = days.rem_euclid(146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = (yoe as i64 + era * 400) as u32;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    let y = if mo <= 2 { y + 1 } else { y };
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}Z")
}

fn write_if_changed(dest: &Path, bytes: &[u8]) {
    if let Ok(existing) = fs::read(dest)
        && existing == bytes
    {
        return;
    }
    // NPKG.3 / B12: actionable failure message — OUT_DIR is cargo-managed,
    // so a write failure here means the build environment is broken (read-
    // only target dir, full disk, exotic filesystem). The panic is the
    // right call: continuing would emit a stale wiki_index.rs.
    fs::write(dest, bytes).unwrap_or_else(|e| {
        panic!(
            "proteus build.rs: cannot write generated wiki index {}: {e}\n\
             hint: OUT_DIR is cargo-managed; check that target/ is writable \
             and the filesystem has free space.",
            dest.display()
        )
    });
}
