// SPDX-License-Identifier: GPL-3.0-or-later
//
// Scans `wiki/*.md` at build time and emits a flat array of
// `(page_name, line_number, byte_offset, byte_len)` for the runtime
// full-text search. Keeping the index small means avoiding a second copy
// of the wiki text in the binary; we slice into the page contents
// returned by `wiki::get_page` at lookup time.
//
// Linear scan is fast enough at this corpus size (~25 pages × ~150 lines
// = ~4000 entries; a case-insensitive scan completes well under 10ms),
// so we skip the inverted-index complexity and keep the binary small.

use std::env;
use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let wiki_dir = manifest_dir.join("wiki");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("wiki_index.rs");

    // `cargo:rerun-if-changed=<dir>` only fires on directory-mtime changes
    // (files added/removed), not on in-place edits to existing files.
    // Emit one `rerun-if-changed` per file inside the loop so editing an
    // existing wiki page also triggers a rebuild (issue #165).
    println!("cargo:rerun-if-changed=wiki");
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if let Ok(read_dir) = fs::read_dir(&wiki_dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            // Track every file we read so cargo invalidates this script when
            // any wiki page is edited in place.
            println!("cargo:rerun-if-changed={}", path.display());
            if path.extension().and_then(OsStr::to_str) != Some("md") {
                continue;
            }
            let Some(stem) = path.file_stem().and_then(OsStr::to_str) else {
                continue;
            };
            // `_index.md` is the curated TOC page; it mentions every other
            // page by name, so leaving it in the search index would always
            // outrank the actual content for broad queries. Skip at index
            // build time and keep `wiki::CURATED_INDEX_PAGE` in sync.
            if stem == "_index" {
                continue;
            }
            entries.push((stem.to_string(), path));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = Vec::with_capacity(64 * 1024);
    writeln!(
        out,
        "// generated by build.rs — do not edit by hand\n\
         //\n\
         // Each entry is (page_name, line_number, byte_offset, byte_len);\n\
         // resolve to text via `&wiki::get_page(page).unwrap()[off..off+len]`.\n\
         pub static WIKI_LINES: &[(&str, u32, u32, u32)] = &["
    )
    .unwrap();

    for (name, path) in &entries {
        let content =
            fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let mut byte_offset: usize = 0;
        let mut line_no: u32 = 0;
        for line in content.split_inclusive('\n') {
            line_no += 1;
            let trimmed = line.trim_end_matches('\n');
            // Skip blank lines: they can't match a search term.
            if !trimmed.trim().is_empty() {
                writeln!(
                    out,
                    "    ({}, {}, {}, {}),",
                    rust_str(name),
                    line_no,
                    byte_offset,
                    trimmed.len()
                )
                .unwrap();
            }
            byte_offset += line.len();
        }
    }
    writeln!(out, "];").unwrap();

    write_if_changed(&dest, &out);
}

/// Emit a `&str` literal that round-trips every char of `s` losslessly.
/// Backslashes, quotes, newlines, tabs, and other control characters are
/// escaped; everything else (including non-ASCII letters and em-dashes)
/// is passed through verbatim — `rustc` accepts arbitrary UTF-8 in `"..."`.
fn rust_str(s: &str) -> String {
    let mut buf = String::with_capacity(s.len() + 2);
    buf.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => buf.push_str("\\\\"),
            '"' => buf.push_str("\\\""),
            '\n' => buf.push_str("\\n"),
            '\r' => buf.push_str("\\r"),
            '\t' => buf.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                buf.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => buf.push(c),
        }
    }
    buf.push('"');
    buf
}

fn write_if_changed(dest: &Path, bytes: &[u8]) {
    if let Ok(existing) = fs::read(dest)
        && existing == bytes
    {
        return;
    }
    fs::write(dest, bytes).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
